INSERT INTO Countries([Name]) VALUES 
('Afghanistan'),
('Argentina'),
('Australia'),
('Austria'),
('Bangladesh'),
('Belgium'),
('Belize'),
('Bhutan'),
('Bolivia'),
('Brazil'),
('Bulgaria'),
('Cambodia'),
('Canada'),
('Chile'),
('China'),
('Colombia'),
('Costa Rica'),
('Cuba'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Fiji'),
('Finland'),
('France'),
('Germany'),
('Greece'),
('Haiti'),
('Honduras'),
('Hong Kong'),
('Hungary'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Kazakhstan'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Malaysia'),
('Maldives'),
('Marshall Islands'),
('Mexico'),
('Micronesia'),
('Mongolia'),
('Myanmar'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Nigeria'),
('North Korea'),
('Norway'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Samoa'),
('Saudi Arabia'),
('Singapore'),
('Solomon Islands'),
('South Africa'),
('South Korea'),
('Spain'),
('Sri Lanka'),
('Sweden'),
('Switzerland'),
('Tajikistan'),
('Taiwan'),
('Thailand'),
('Tonga'),
('Trinidad and Tobago'),
('Turkmenistan'),
('Tuvalu'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe');


INSERT INTO Cities(Name, CountryId) VALUES
('Kabul', 1), ('Kandahar', 1), ('Herat', 1), ('Mazar-i-Sharif', 1), ('Jalalabad', 1),
('Buenos Aires', 2), ('Córdoba', 2), ('Rosario', 2), ('Mendoza', 2), ('San Miguel de Tucumán', 2),
('Sydney', 3), ('Melbourne', 3), ('Brisbane', 3), ('Perth', 3), ('Adelaide', 3),
('Vienna', 4), ('Graz', 4), ('Linz', 4), ('Salzburg', 4), ('Innsbruck', 4),
('Dhaka', 5), ('Chittagong', 5), ('Khulna', 5), ('Rajshahi', 5), ('Sylhet', 5),
('Brussels', 6), ('Antwerp', 6), ('Ghent', 6), ('Bruges', 6), ('Liege', 6),
('Belize City', 7), ('San Ignacio', 7), ('Belmopan', 7), ('Orange Walk', 7), ('Dangriga', 7),
('Thimphu', 8), ('Phuntsholing', 8), ('Paro', 8), ('Punakha', 8), ('Jakar', 8),
('La Paz', 9), ('Sucre', 9), ('Santa Cruz de la Sierra', 9), ('Cochabamba', 9), ('Oruro', 9),
('São Paulo', 10), ('Rio de Janeiro', 10), ('Brasília', 10), ('Salvador', 10), ('Fortaleza', 10),
('Sofia', 11), ('Plovdiv', 11), ('Varna', 11), ('Burgas', 11), ('Ruse', 11),
('Phnom Penh', 12), ('Siem Reap', 12), ('Battambang', 12), ('Sihanoukville', 12), ('Kampong Cham', 12),
('Toronto', 13), ('Montreal', 13), ('Vancouver', 13), ('Calgary', 13), ('Edmonton', 13),
('Santiago', 14), ('Valparaíso', 14), ('Concepción', 14), ('Antofagasta', 14), ('Temuco', 14),
('Beijing', 15), ('Shanghai', 15), ('Guangzhou', 15), ('Shenzhen', 15), ('Chengdu', 15),
('Bogotá', 16), ('Medellín', 16), ('Cali', 16), ('Barranquilla', 16), ('Cartagena', 16),
('San Jose', 17), ('Limón', 17), ('Heredia', 17), ('Alajuela', 17), ('Puntarenas', 17),
('Havana', 18), ('Santiago de Cuba', 18), ('Camagüey', 18), ('Holguín', 18), ('Santa Clara', 18),
('Santo Domingo', 19), ('Santiago de los Caballeros', 19), ('Santo Domingo Este', 19), ('Santo Domingo Oeste', 19), ('Santo Domingo Norte', 19),
('Quito', 20), ('Guayaquil', 20), ('Cuenca', 20), ('Ambato', 20), ('Santo Domingo de los Colorados', 20),
('Cairo', 21), ('Alexandria', 21), ('Giza', 21), ('Shubra El Kheima', 21), ('Port Said', 21),
('San Salvador', 22), ('Santa Ana', 22), ('San Miguel', 22), ('Soyapango', 22), ('Mejicanos', 22),
('Suva', 23), ('Lautoka', 23), ('Nadi', 23), ('Labasa', 23), ('Ba', 23),
('Helsinki', 24), ('Espoo', 24), ('Tampere', 24), ('Vantaa', 24), ('Oulu', 24),
('Paris', 25), ('Marseille', 25), ('Lyon', 25), ('Toulouse', 25), ('Nice', 25),
('Berlin', 26), ('Hamburg', 26), ('Munich', 26), ('Cologne', 26), ('Frankfurt', 26),
('Athens', 27), ('Thessaloniki', 27), ('Patras', 27), ('Heraklion', 27), ('Larissa', 27),
('Port-au-Prince', 28), ('Carrefour', 28), ('Delmas', 28), ('Pétion-Ville', 28), ('Gonaïves', 28),
('Tegucigalpa', 29), ('San Pedro Sula', 29), ('Choloma', 29), ('La Ceiba', 29), ('Comayagua', 29),
('Hong Kong', 30), ('Kowloon', 30), ('Tsuen Wan', 30), ('Yuen Long Kau Hui', 30), ('Tuen Mun', 30),
('Budapest', 31), ('Debrecen', 31), ('Szeged', 31), ('Miskolc', 31), ('Pécs', 31),
('Mumbai', 32), ('Delhi', 32), ('Bangalore', 32), ('Hyderabad', 32), ('Chennai', 32),
('Jakarta', 33), ('Surabaya', 33), ('Bandung', 33), ('Medan', 33), ('Semarang', 33),
('Tehran', 34), ('Mashhad', 34), ('Isfahan', 34), ('Karaj', 34), ('Tabriz', 34),
('Baghdad', 35), ('Basra', 35), ('Mosul', 35), ('Erbil', 35), ('Najaf', 35),
('Jerusalem', 36), ('Tel Aviv', 36), ('Haifa', 36), ('Rishon LeZion', 36), ('Petah Tikva', 36),
('Rome', 37), ('Milan', 37), ('Naples', 37), ('Turin', 37), ('Palermo', 37),
('Kingston', 38), ('Spanish Town', 38), ('Portmore', 38), ('Montego Bay', 38), ('Mandeville', 38),
('Tokyo', 39), ('Yokohama', 39), ('Osaka', 39), ('Nagoya', 39), ('Sapporo', 39),
('Almaty', 40), ('Nur-Sultan', 40), ('Shymkent', 40), ('Karaganda', 40), ('Aktobe', 40),
('Kuwait City', 41), ('Al Ahmadi', 41), ('Hawalli', 41), ('Farwaniya', 41), ('Jahra', 41),
('Bishkek', 42), ('Osh', 42), ('Jalal-Abad', 42), ('Karakol', 42), ('Tokmok', 42),
('Vientiane', 43), ('Pakse', 43), ('Savannakhet', 43), ('Luang Prabang', 43), ('Xam Neua', 43),
('Kuala Lumpur', 44), ('George Town', 44), ('Ipoh', 44), ('Shah Alam', 44), ('Petaling Jaya', 44),
('Malé', 45), ('Addu City', 45), ('Fuvahmulah', 45), ('Kulhudhuffushi', 45), ('Thinadhoo', 45),
('Majuro', 46),
('Mexico City', 47), ('Guadalajara', 47), ('Monterrey', 47), ('Puebla', 47), ('Tijuana', 47),
('Palikir', 48),
('Ulaanbaatar', 49), ('Darkhan', 49), ('Erdenet', 49), ('Choibalsan', 49), ('Khovd', 49),
('Yangon', 50), ('Mandalay', 50), ('Naypyidaw', 50), ('Mawlamyine', 50), ('Bago', 50),
('Yaren', 51),
('Kathmandu', 52), ('Pokhara', 52), ('Lalitpur', 52), ('Bharatpur', 52), ('Biratnagar', 52),
('Amsterdam', 53), ('Rotterdam', 53), ('The Hague', 53), ('Utrecht', 53), ('Eindhoven', 53),
('Auckland', 54), ('Wellington', 54), ('Christchurch', 54), ('Hamilton', 54), ('Tauranga', 54),
('Managua', 55), ('León', 55), ('Masaya', 55), ('Matagalpa', 55), ('Chinandega', 55),
('Lagos', 56), ('Kano', 56), ('Ibadan', 56), ('Kaduna', 56), ('Port Harcourt', 56),
('Pyongyang', 57),
('Oslo', 58), ('Bergen', 58), ('Stavanger', 58), ('Trondheim', 58), ('Drammen', 58),
('Karachi', 59), ('Lahore', 59), ('Faisalabad', 59), ('Rawalpindi', 59), ('Multan', 59),
('Ngerulmud', 60),
('Panama City', 61), ('San Miguelito', 61), ('Tocumen', 61), ('David', 61), ('Arraiján', 61),
('Port Moresby', 62), ('Lae', 62), ('Mount Hagen', 62), ('Madang', 62), ('Goroka', 62),
('Asunción', 63), ('Ciudad del Este', 63), ('San Lorenzo', 63), ('Capiatá', 63), ('Lambaré', 63),
('Lima', 64), ('Arequipa', 64), ('Callao', 64), ('Trujillo', 64), ('Chiclayo', 64),
('Manila', 65), ('Quezon City', 65), ('Davao City', 65), ('Cebu City', 65), ('Zamboanga City', 65),
('Warsaw', 66), ('Kraków', 66), ('Łódź', 66), ('Wrocław', 66), ('Poznań', 66),
('Lisbon', 67), ('Porto', 67), ('Amadora', 67), ('Braga', 67), ('Coimbra', 67),
('Doha', 68), ('Al Rayyan', 68), ('Umm Salal', 68), ('Al Wakrah', 68), ('Al Khor', 68),
('Bucharest', 69), ('Cluj-Napoca', 69), ('Timișoara', 69), ('Iași', 69), ('Constanța', 69),
('Moscow', 70), ('Saint Petersburg', 70), ('Yekaterinburg', 70), ('Nizhny Novgorod', 70),
('Apia', 71),
('Riyadh', 72), ('Jeddah', 72), ('Mecca', 72), ('Medina', 72), ('Dammam', 72),
('Singapore', 73),
('Honiara', 74),
('Johannesburg', 75), ('Cape Town', 75), ('Durban', 75), ('Pretoria', 75), ('Port Elizabeth', 75),
('Seoul', 76), ('Busan', 76), ('Incheon', 76), ('Daegu', 76), ('Daejeon', 76),
('Madrid', 77), ('Barcelona', 77), ('Valencia', 77), ('Seville', 77), ('Zaragoza', 77),
('Colombo', 78), ('Dehiwala-Mount Lavinia', 78), ('Moratuwa', 78), ('Jaffna', 78), ('Negombo', 78),
('Stockholm', 79), ('Gothenburg', 79), ('Malmö', 79), ('Uppsala', 79), ('Linköping', 79),
('Zurich', 80), ('Geneva', 80), ('Basel', 80), ('Bern', 80), ('Lausanne', 80),
('Dushanbe', 81), ('Khujand', 81), ('Kulob', 81), ('Qurghonteppa', 81), ('Istaravshan', 81),
('Taipei', 82), ('New Taipei', 82), ('Kaohsiung', 82), ('Taichung', 82), ('Tainan', 82),
('Bangkok', 83), ('Nonthaburi', 83), ('Samut Prakan', 83), ('Chiang Mai', 83), ('Hat Yai', 83),
('Nukuʻalofa', 84),
('Port of Spain', 85), ('Chaguanas', 85), ('San Fernando', 85), ('Arima', 85), ('Marabella', 85),
('Ashgabat', 86), ('Türkmenabat', 86), ('Daşoguz', 86), ('Mary', 86), ('Balkanabat', 86),
('Funafuti', 87),
('Kyiv', 88), ('Kharkiv', 88), ('Odesa', 88), ('Dnipro', 88), ('Donetsk', 88),
('Dubai', 89), ('Abu Dhabi', 89), ('Sharjah', 89), ('Al Ain', 89), ('Ajman', 89),
('London', 90), ('Birmingham', 90), ('Manchester', 90), ('Glasgow', 90), ('Liverpool', 90),
('New York City', 91), ('Los Angeles', 91), ('Chicago', 91), ('Houston', 91), ('Phoenix', 91),
('Montevideo', 92), ('Salto', 92), ('Ciudad de la Costa', 92), ('Paysandú', 92), ('Las Piedras', 92),
('Tashkent', 93), ('Namangan', 93), ('Samarkand', 93), ('Andijan', 93), ('Bukhara', 93),
('Port Vila', 94),
('Caracas', 95), ('Maracaibo', 95), ('Valencia', 95), ('Barquisimeto', 95), ('Maracay', 95),
('Ho Chi Minh City', 96), ('Hanoi', 96), ('Da Nang', 96), ('Hai Phong', 96), ('Can Tho', 96),
('Sanaa', 97), ('Aden', 97), ('Taiz', 97), ('Al Hudaydah', 97), ('Ibb', 97),
('Lusaka', 98), ('Kitwe', 98), ('Ndola', 98), ('Kabwe', 98), ('Chingola', 98),
('Harare', 99), ('Bulawayo', 99), ('Chitungwiza', 99), ('Mutare', 99), ('Gweru', 99);